### ISSUE TITLE
Fix pier correction database values

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/geomag-web-absolutes#255]
- Based on documentation generated by #252, fix remaining observatory pier correction values in database.

**Comment by aclaycomb-usgs** [comment]
As of 8/29/16, I've corrected  the database as far back as we have baselines entered.  Work can be saved.  More updates  are scheduled for Wednesday.

**Comment by jmfee-usgs** [comment]
We will reopen if any new issues are found.
