### ISSUE TITLE
Show warning for future time values

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/geomag-web-absolutes#257]
- Show warning if measurement time is in the future (possibly short-circuit data request).

**Comment by jmfee-usgs** [comment]
MeasurementView does some time validation already, currently for format instead of whether time is in future:
https://github.com/usgs/geomag-web-absolutes/blob/master/src/htdocs/js/geomag/MeasurementView.js#L147

Realtime data is fetched by ObservationView.  This could set a "loading" property on each measurement, and use the success and an (added) error callback to update the "loading" property on each measurement once data is loaded...
https://github.com/usgs/geomag-web-absolutes/blob/master/src/htdocs/js/geomag/ObservationView.js#L262
https://github.com/usgs/geomag-web-absolutes/blob/master/src/htdocs/js/geomag/Measurement.js#L47

**Comment by aclaycomb-usgs** [comment]
It now doesn't clear the error at the bottom of the page when you fix the future time.  It used to before.
